blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://upstash.com/discord
    about: Ask the community for help
  - name: Report a security issue
    url: https://github.com/upstash/vector-php/security/policy
    about: Learn how to notify us for sensitive bugs
